<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>Madbox.LiveOps.DTO</AssemblyName>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <UnityPluginsDir>$(MSBuildThisFileDirectory)..\..\Assets\Plugins\Madbox.LiveOps.DTO\</UnityPluginsDir>
  </PropertyGroup>
  <Target Name="CopyDtoToUnityPlugins" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)" DestinationFiles="$(UnityPluginsDir)$(TargetFileName)" SkipUnchangedFiles="false" />
    <Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFiles="$(UnityPluginsDir)$(TargetName).pdb" SkipUnchangedFiles="true" Condition="Exists('$(TargetDir)$(TargetName).pdb')" />
  </Target>
</Project>
